apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - name: 4111-3111
    port: {{ .Values.namespace.port }}
    protocol: TCP
    targetPort: {{ .Values.namespace.port }}
  selector:
    app: techtrends
  type: {{ .Values.namespace.type }}
